Snapshot
openintegrationhub/component-generator pull request #13
Opened 2022-01-10 08:41 UTC by IoannisLafiotis

2022-01-12 13:12 UTC, weberjm reviewed
Please check my comments. If we need to have a chat to go over somethign I missed, let me know.

2022-01-12 13:12 UTC, weberjm commented on templates/trigger.js
> +  snapshot.lastUpdated = snapshot.lastUpdated || (new Date(0)).getTime();
What happens if the snapshot field for a service is not called "lastUpdated"? It seems from the updates to generate.js and trigger.js, that the snapshot is still never saved to the service again.

2022-01-18 11:38 UTC, weberjm requested changes
Hi Ioannis, lots of good updates here. Please check the items I mentioned and resolve / reply to the comments.

2022-01-18 11:38 UTC, weberjm commented on .gitignore
Please at the .vscode/ file to your .gitignore

2022-01-18 11:38 UTC, weberjm commented on generate.sh
> +function addInterceptor () {
This file is very inflexible in its usage. Instead of providing a set of steps which is necessary for all components, it uses hardcoded names in many locations, and will require code updates whenever new components are added, or even if a name is changed (i.e. line 15 with the SevDesk components).

This is likely useful to you, and maybe the rest of the platform team, but would be of minimal external value.

2022-01-18 11:38 UTC, weberjm commented on generate.sh
> +function addInterceptor () {
I would suggest maintaining this script outside of the component-generator, possibly in a "scripts" repo in the corporate org, rather than the open source org

2022-01-18 11:38 UTC, weberjm commented on templates/action.js
> +  $SECURITIES;
Will this semicolon added to the template placeholder cause a dangling semicolon in the output file?

2022-01-18 11:38 UTC, weberjm commented on templates/action.js
> +    spec.servers.push({ url: cfg.otherServer });
Have you tested this output to ensure it works with the quotes removed? I think this is ok, but want to make sure we don't introduce a regression.

2022-01-18 11:38 UTC, weberjm commented on templates/helpers.js
> +const moment = require('moment');
Adding moment for just this one function is probably overkill. moment is now in maintenance mode (https://momentjs.com/docs/) and it would probably be a good idea to consider a more "modern" library here.

2022-01-18 12:37 UTC, IoannisLafiotis commented on .gitignore
I will add them to different file

2022-01-18 12:37 UTC, IoannisLafiotis commented on generate.sh
> +function addInterceptor () {
As I said above I will remove the script from the generator

2022-01-18 12:38 UTC, IoannisLafiotis commented on templates/action.js
> +  $SECURITIES;
I will repush so the problem will disappear.

2022-01-18 12:46 UTC, IoannisLafiotis commented on .gitignore
Removed them from the generator

2022-01-18 12:46 UTC, IoannisLafiotis commented on generate.sh
> +function addInterceptor () {
Ok already removed

2022-01-18 12:47 UTC, IoannisLafiotis commented on templates/action.js
> +  $SECURITIES;
Yes you were right oon this one, I fixed it with the last push

2022-01-18 12:48 UTC, IoannisLafiotis commented on templates/action.js
> +    spec.servers.push({ url: cfg.otherServer });
I did run prettier on the file and it changed the quotes. I have requoted it!

2022-01-18 12:48 UTC, IoannisLafiotis commented on templates/helpers.js
> +const moment = require('moment');
I can take a look to some other libs

2022-01-18 13:43 UTC, weberjm commented on .gitignore
Hey @IoannisLafiotis, my point was that you have a file now in the repo called '.vscode/settings.json'  This file, and any other VSCode config files, should not be included in the repo, and so you should add a line to the .gitignore for '.vscode/'

2022-01-18 13:46 UTC, weberjm reviewed
Almost there,  just  an update to .gitignore, and checking on moment!

2022-01-18 14:08 UTC, IoannisLafiotis commented on templates/trigger.js
> +  snapshot.lastUpdated = snapshot.lastUpdated || (new Date(0)).getTime();
That is solved in the latest push

2022-01-18 17:14 UTC, IoannisLafiotis commented on .gitignore
Maybe I will remove it completely since the pretttify on save func is not really needed.

2022-01-20 13:33 UTC, weberjm approved these changes

2022-01-20 14:48 UTC, merged