Codesplitdoc
openintegrationhub/component-generator pull request #18
Opened 2022-03-20 09:30 UTC by IoannisLafiotis

- Added the README specifications for the code improvmeents
- Removed the paperless.yml file that had no use to the rest of the code

2022-03-22 21:29 UTC, weberjm requested changes

2022-03-22 21:29 UTC, weberjm commented on lib/utils/addCredentialsForComponentJson.js
> +        case 'BasicAuth' || 'bearerAuth' || 'BearerAuth':
Bearer Auth is not a form of basic auth. It uses the Authorisation header Bearer instead of Basic, and contains a token rather than a Base64 encoded username:password set

2022-03-22 21:29 UTC, weberjm commented on lib/utils/addCredentialsForComponentJson.js
> +              'We require that applications designed to access the Asana API on behalf of multiple users implement OAuth 2.0.\nAsana supports the Authorization Code Grant flow.',
Should not hardcode references to a specific third party solution (here, Asana)

2022-03-24 09:24 UTC, IoannisLafiotis commented on lib/utils/addCredentialsForComponentJson.js
> +              'We require that applications designed to access the Asana API on behalf of multiple users implement OAuth 2.0.\nAsana supports the Authorization Code Grant flow.',
I changed that to a generic name.

2022-03-24 09:24 UTC, IoannisLafiotis commented on lib/utils/addCredentialsForComponentJson.js
> +        case 'BasicAuth' || 'bearerAuth' || 'BearerAuth':
Separated the basic and the bearer in 2 different cases.

2022-05-03 14:34 UTC, IoannisLafiotis commented
In case of multiple contentTypes should we select the first header or just set is to application/json?

2022-05-03 15:39 UTC, weberjm requested changes
Make sure to remove logs. Other comments can be implemented now, or via separate ticket at a later point

2022-05-03 15:39 UTC, weberjm commented on lib/utils/createActionAndSecuritySchemes.js
> +      'What is your security scheme/s ex. ( BasicAuth apiKey OAuth2 )? '
Since we are looking at using the generator also embedded in other applications, using 'prompt' would likely break on this use case. The other places where prompts are made is within the questionnaire, that allows for passing defaults only. Please consider if there is a way to pass a default to this location also, or create an issue to implement this use case in the short-term

2022-05-03 15:39 UTC, weberjm commented on lib/utils/createActionAndSecuritySchemes.js
> +    console.log('here too');
Remove test logs

2022-05-03 15:39 UTC, weberjm commented on lib/utils/createActionAndSecuritySchemes.js
> +        console.log('here too');
Remove test logs

2022-05-03 15:39 UTC, weberjm commented on lib/utils/schemaAndComponentJsonBuilder.js
> +            action.callParams['requestContentType'] = `${contentTypes[0]}`;
As discussed in meeting, is there a way to prioritise 'application\json'? If not, this output is fine.

2022-05-04 10:13 UTC, IoannisLafiotis commented on lib/utils/createActionAndSecuritySchemes.js
> +        console.log('here too');
I removed the logs

2022-05-04 10:14 UTC, IoannisLafiotis commented on lib/utils/schemaAndComponentJsonBuilder.js
> +            action.callParams['requestContentType'] = `${contentTypes[0]}`;
I prioritise the application json header if it exists other wise we will take the first element of the array!

2022-05-11 13:19 UTC, merged